"""Skibidi uživatel

Revision ID: 0b01fd678f17
Revises: 172893f2c4d0
Create Date: 2025-05-13 19:08:45.587288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b01fd678f17'
down_revision = '172893f2c4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.drop_column('idClass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idClass', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_ibfk_1', 'class', ['idClass'], ['id'])

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
