"""Conversation cascade on idUser

Revision ID: 0d149bea5d81
Revises: ad8d7660b640
Create Date: 2026-04-30 17:02:28.731166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d149bea5d81'
down_revision = 'ad8d7660b640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint('conversation_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('conversation_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['idUser2'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['idUser1'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('conversation_ibfk_2', 'user', ['idUser1'], ['id'])
        batch_op.create_foreign_key('conversation_ibfk_3', 'user', ['idUser2'], ['id'])

    # ### end Alembic commands ###
