"""Team test

Revision ID: 0f91c5325743
Revises: c29c758c79d6
Create Date: 2025-12-30 12:39:16.664197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f91c5325743'
down_revision = 'c29c758c79d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.drop_constraint('user_team_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['idTask'], ['idTask'])

    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.drop_constraint('version_team_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['idTask'], ['idTask'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('version_team_ibfk_2', 'task', ['idTask'], ['id'])

    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_team_ibfk_3', 'task', ['idTask'], ['id'])

    # ### end Alembic commands ###
