"""Small change with event

Revision ID: 0fb994956840
Revises: 67bb0cf49e71
Create Date: 2026-02-20 15:30:15.854255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fb994956840'
down_revision = '67bb0cf49e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('idUser',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('ByTeacher', 'Own', 'Task'),
               nullable=True)

    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('ByTeacher', 'Own', 'Task'),
               nullable=False)
        batch_op.alter_column('idUser',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)

    # ### end Alembic commands ###
