"""Skibidní migrace

Revision ID: 172893f2c4d0
Revises: 
Create Date: 2025-05-09 21:00:48.160296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '172893f2c4d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('elaboration',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('review',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('elaboration',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
