"""Little class change

Revision ID: 2a3444cc0d55
Revises: 2acd88c81f00
Create Date: 2025-05-15 18:24:00.986118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a3444cc0d55'
down_revision = '2acd88c81f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('team',
    sa.Column('idUser', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idTask', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leader', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idTask'], ['task.id'], name='team_ibfk_2'),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], name='team_ibfk_1'),
    sa.PrimaryKeyConstraint('idUser', 'idTask'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
