"""Uhr uhr

Revision ID: 2acd88c81f00
Revises: 0b01fd678f17
Create Date: 2025-05-14 17:19:30.490527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2acd88c81f00'
down_revision = '0b01fd678f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approve', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('elaboration')
        batch_op.drop_column('review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('elaboration', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('approve')

    op.create_table('team',
    sa.Column('idUser', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idTask', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leader', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idTask'], ['task.id'], name='team_ibfk_2'),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], name='team_ibfk_1'),
    sa.PrimaryKeyConstraint('idUser', 'idTask'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
