"""Added conversations

Revision ID: 2bc2c2fe6a8d
Revises: f0cbbc407108
Create Date: 2026-02-17 22:40:18.095246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bc2c2fe6a8d'
down_revision = 'f0cbbc407108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('idConversation', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idUser1', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('idUser2', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('idTask', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('guarantor', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('isArchived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idTask', 'guarantor'], ['task.id', 'task.guarantor'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idUser1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['idUser2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('idConversation')
    )
    op.create_table('message',
    sa.Column('idMessage', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('idConversation', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('sender', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replyToMessage', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['idConversation'], ['conversation.idConversation'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], ),
    sa.PrimaryKeyConstraint('idMessage', 'idConversation')
    )
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_constraint('class_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialization', ['idSpecialization'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('evaluator', schema=None) as batch_op:
        batch_op.drop_constraint('evaluator_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('evaluator_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'maturita', ['idMaturita'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['idUser'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
        batch_op.drop_constraint('maturita_task_ibfk_5', type_='foreignkey')
        batch_op.drop_constraint('maturita_task_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('maturita_task_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['idTask', 'guarantor'], ['id', 'guarantor'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'maturita', ['idMaturita'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'topic', ['idTopic'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['guarantor'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('team_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['idTask', 'guarantor'], ['id', 'guarantor'], ondelete='CASCADE')

    with op.batch_alter_table('user_class', schema=None) as batch_op:
        batch_op.drop_constraint('user_class_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('user_class_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['idUser'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'class', ['idClass'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.drop_constraint('user_team_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('user_team_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['idUser'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'team', ['idTask', 'guarantor', 'idTeam'], ['idTask', 'guarantor', 'idTeam'], ondelete='CASCADE')

    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.drop_constraint('version_team_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['idTask', 'guarantor', 'idTeam'], ['idTask', 'guarantor', 'idTeam'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('version_team_ibfk_1', 'team', ['idTask', 'guarantor', 'idTeam'], ['idTask', 'guarantor', 'idTeam'])

    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_team_ibfk_2', 'user', ['idUser'], ['id'])
        batch_op.create_foreign_key('user_team_ibfk_1', 'team', ['idTask', 'guarantor', 'idTeam'], ['idTask', 'guarantor', 'idTeam'])

    with op.batch_alter_table('user_class', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_class_ibfk_2', 'class', ['idClass'], ['id'])
        batch_op.create_foreign_key('user_class_ibfk_1', 'user', ['idUser'], ['id'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('team_ibfk_1', 'task', ['idTask', 'guarantor'], ['id', 'guarantor'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_ibfk_1', 'user', ['guarantor'], ['id'])

    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('maturita_task_ibfk_1', 'task', ['idTask', 'guarantor'], ['id', 'guarantor'])
        batch_op.create_foreign_key('maturita_task_ibfk_2', 'topic', ['idTopic'], ['id'])
        batch_op.create_foreign_key('maturita_task_ibfk_5', 'maturita', ['idMaturita'], ['id'])
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)

    with op.batch_alter_table('evaluator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('evaluator_ibfk_1', 'user', ['idUser'], ['id'])
        batch_op.create_foreign_key('evaluator_ibfk_2', 'maturita', ['idMaturita'], ['id'])

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('class_ibfk_1', 'specialization', ['idSpecialization'], ['id'])

    op.drop_table('message')
    op.drop_table('conversation')
    # ### end Alembic commands ###
