"""Small change

Revision ID: 3a25adaf9db0
Revises: 7927da2b19be
Create Date: 2026-02-21 09:55:06.446459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a25adaf9db0'
down_revision = '7927da2b19be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('ByTeacher', 'Own', 'Task'),
               type_=sa.Enum('ByOther', 'Own', 'Task', name='event_type'),
               existing_nullable=True)

    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('ByOther', 'Own', 'Task', name='event_type'),
               type_=mysql.ENUM('ByTeacher', 'Own', 'Task'),
               existing_nullable=True)

    # ### end Alembic commands ###
