"""Changed integers and so on to unsigned

Revision ID: 4a4830b37470
Revises: e7b0c9a8d088
Create Date: 2025-12-05 22:46:06.287685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a4830b37470'
down_revision = 'e7b0c9a8d088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_task')
    op.drop_table('task_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_class',
    sa.Column('idTask', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('idClass', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idClass'], ['class.id'], name='task_class_ibfk_2'),
    sa.ForeignKeyConstraint(['idTask'], ['task.id'], name='task_class_ibfk_1'),
    sa.PrimaryKeyConstraint('idTask', 'idClass'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_task',
    sa.Column('idUser', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('idTask', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('elaboration', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('review', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['idTask'], ['task.id'], name='user_task_ibfk_2'),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], name='user_task_ibfk_1'),
    sa.PrimaryKeyConstraint('idUser', 'idTask'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
