"""Small change with event

Revision ID: 7927da2b19be
Revises: 0fb994956840
Create Date: 2026-02-20 19:15:21.024010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7927da2b19be'
down_revision = '0fb994956840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
