"""Já fakt nevím

Revision ID: 941b8ef2e6b3
Revises: 2a3444cc0d55
Create Date: 2025-05-22 18:57:53.300343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '941b8ef2e6b3'
down_revision = '2a3444cc0d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    with op.batch_alter_table('specialization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbreviation', sa.CHAR(length=1), nullable=False))
        batch_op.create_unique_constraint(None, ['abbreviation'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbrevation', mysql.CHAR(length=1), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('abbrevation', ['abbrevation'], unique=True)
        batch_op.drop_column('abbreviation')

    # ### end Alembic commands ###
