"""Já fakt nevím

Revision ID: 941b8ef2e6b3
Revises: 2a3444cc0d55
Create Date: 2025-05-22 18:57:53.300343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '941b8ef2e6b3'
down_revision = '2a3444cc0d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    with op.batch_alter_table('specialization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbreviation', sa.CHAR(length=1), nullable=False))
        batch_op.drop_index('abbrevation')
        batch_op.create_unique_constraint(None, ['abbreviation'])
        batch_op.drop_column('abbrevation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbrevation', mysql.CHAR(length=1), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('abbrevation', ['abbrevation'], unique=True)
        batch_op.drop_column('abbreviation')

    op.create_table('team',
    sa.Column('idUser', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idTask', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leader', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idTask'], ['task.id'], name='team_ibfk_2'),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], name='team_ibfk_1'),
    sa.PrimaryKeyConstraint('idUser', 'idTask'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
