"""Idk

Revision ID: a06567438ae4
Revises: bb01c49ea7c9
Create Date: 2026-01-02 23:42:01.206018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a06567438ae4'
down_revision = 'bb01c49ea7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
