"""Team test2

Revision ID: b00cacbfb66c
Revises: 0f91c5325743
Create Date: 2025-12-30 12:50:25.819803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00cacbfb66c'
down_revision = '0f91c5325743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.drop_constraint('user_team_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_team_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['idTeam', 'idTask'], ['idTeam', 'idTask'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_team_ibfk_3', 'team', ['idTask'], ['idTask'])
        batch_op.create_foreign_key('user_team_ibfk_2', 'team', ['idTeam'], ['idTeam'])

    # ### end Alembic commands ###
