"""Small change

Revision ID: b0e10aa11e70
Revises: eb04608f6078
Create Date: 2026-02-11 11:26:35.864462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0e10aa11e70'
down_revision = 'eb04608f6078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)

    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)

    # ### end Alembic commands ###
