"""Changed updatedAt to createdAt in version_team

Revision ID: bb01c49ea7c9
Revises: bf632feaea8b
Create Date: 2026-01-02 22:50:38.964325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb01c49ea7c9'
down_revision = 'bf632feaea8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.drop_column('updatedAt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('createdAt')

    # ### end Alembic commands ###
