"""Team test3

Revision ID: bf632feaea8b
Revises: b00cacbfb66c
Create Date: 2025-12-30 12:52:29.105087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf632feaea8b'
down_revision = 'b00cacbfb66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.drop_constraint('version_team_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('version_team_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['idTeam', 'idTask'], ['idTeam', 'idTask'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('version_team_ibfk_1', 'team', ['idTeam'], ['idTeam'])
        batch_op.create_foreign_key('version_team_ibfk_2', 'team', ['idTask'], ['idTask'])

    # ### end Alembic commands ###
