"""Small change with maturitas

Revision ID: c1d6c964f497
Revises: 
Create Date: 2026-01-31 23:10:05.250788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1d6c964f497'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturita', schema=None) as batch_op:
        batch_op.alter_column('startDate',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('endDate',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('startDate',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('endDate',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('deadline',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('reviewUpdatedAt',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('teamUpdatedAt',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updatedAt',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=mysql.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('updatedAt',
               existing_type=mysql.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('createdAt',
               existing_type=mysql.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('teamUpdatedAt',
               existing_type=mysql.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('reviewUpdatedAt',
               existing_type=mysql.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=mysql.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('endDate',
               existing_type=mysql.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('startDate',
               existing_type=mysql.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)

    with op.batch_alter_table('maturita', schema=None) as batch_op:
        batch_op.alter_column('endDate',
               existing_type=mysql.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('startDate',
               existing_type=mysql.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
