"""added updatedAt to team and version_team

Revision ID: c29c758c79d6
Revises: e5d4e230ae68
Create Date: 2025-12-29 22:49:04.798602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29c758c79d6'
down_revision = 'e5d4e230ae68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewUpdatedAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('teamUpdatedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('teamUpdatedAt')
        batch_op.drop_column('reviewUpdatedAt')

    # ### end Alembic commands ###
