"""Added deadline to tasks

Revision ID: e7b0c9a8d088
Revises: 9b0a7ece0e14
Create Date: 2025-10-30 18:11:32.282589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7b0c9a8d088'
down_revision = '9b0a7ece0e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_class')
    op.drop_table('user_task')
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.alter_column('group',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.Enum('Maturita', 'Task', name='type'), nullable=False))
        batch_op.add_column(sa.Column('points', sa.Float(), nullable=True))
        batch_op.drop_column('approve')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminders', sa.Boolean(), nullable=False))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.Enum('Student', 'Teacher', 'Admin', name='role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('Student', 'Teacher', 'Admin', name='role'),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
        batch_op.drop_column('reminders')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approve', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('points')
        batch_op.drop_column('type')
        batch_op.drop_column('deadline')

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.alter_column('group',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               existing_nullable=False)

    op.create_table('user_task',
    sa.Column('idUser', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('idTask', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('elaboration', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('review', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['idTask'], ['task.id'], name='user_task_ibfk_2'),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], name='user_task_ibfk_1'),
    sa.PrimaryKeyConstraint('idUser', 'idTask'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('task_class',
    sa.Column('idTask', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('idClass', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idClass'], ['class.id'], name='task_class_ibfk_2'),
    sa.ForeignKeyConstraint(['idTask'], ['task.id'], name='task_class_ibfk_1'),
    sa.PrimaryKeyConstraint('idTask', 'idClass'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
