"""Small change with foreign keys

Revision ID: eb04608f6078
Revises: 
Create Date: 2026-02-01 18:51:33.891294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb04608f6078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
        batch_op.alter_column('variant',
               existing_type=mysql.CHAR(length=1),
               nullable=True)
        batch_op.drop_constraint('maturita_task_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('maturita_task_ibfk_3', type_='foreignkey')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('team_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('team_ibfk_2', type_='foreignkey')

    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.drop_constraint('user_team_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('user_team_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('user_team_ibfk_5', type_='foreignkey')

    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.drop_constraint('version_team_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('version_team_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('version_team_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_team', schema=None) as batch_op:
        batch_op.create_foreign_key('version_team_ibfk_2', 'team', ['idTeam'], ['idTeam'])
        batch_op.create_foreign_key('version_team_ibfk_4', 'team', ['guarantor'], ['guarantor'])
        batch_op.create_foreign_key('version_team_ibfk_3', 'team', ['idTask'], ['idTask'])

    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.create_foreign_key('user_team_ibfk_5', 'team', ['guarantor'], ['guarantor'])
        batch_op.create_foreign_key('user_team_ibfk_3', 'team', ['idTeam'], ['idTeam'])
        batch_op.create_foreign_key('user_team_ibfk_4', 'team', ['idTask'], ['idTask'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_foreign_key('team_ibfk_2', 'task', ['idTask'], ['id'])
        batch_op.create_foreign_key('team_ibfk_3', 'task', ['guarantor'], ['guarantor'])

    with op.batch_alter_table('maturita_task', schema=None) as batch_op:
        batch_op.create_foreign_key('maturita_task_ibfk_3', 'task', ['idTask'], ['id'])
        batch_op.create_foreign_key('maturita_task_ibfk_4', 'task', ['guarantor'], ['guarantor'])
        batch_op.alter_column('variant',
               existing_type=mysql.CHAR(length=1),
               nullable=False)
        batch_op.alter_column('idMaturita',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)

    # ### end Alembic commands ###
