name: Deploy Python Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop old containers
        run: |
          cd ~/INOSU-Backend
          docker compose down || true

      - name: Build Docker image(s)
        run: |
          cd ~/INOSU-Backend
          docker compose build

      - name: Start backend service
        run: |
          cd ~/INOSU-Backend
          docker compose up -d

      - name: Clean up unused Docker resources
        run: |
          docker system prune -af || true
